stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes..."
    - kubectl apply -f k8s/deployment.yaml
  environment:
    name: production
    url: http://localhost
  only:
    - main
