Vagrant.configure("2") do |configu|
  # Disable vbguest auto updates, it might cause issues with VirtualBox on M1
  # configu.vbguest.auto_update = false

  configu.vm.define "melkarmiW" do |control|
    control.vm.box = "bento/ubuntu-20.04-arm64"
    control.vm.hostname = "melkarmiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "vmware_fusion" do |vb|
        vb.cpus = 1
        vb.memory = "1024"
      end

    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - server \
      --node-ip=192.168.56.110 \
      --tls-san=192.168.56.110 \
      --write-kubeconfig-mode 644
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node_token
      sudo touch /vagrant/server_ready
    SHELL
  end

  configu.vm.define "ozakkare" do |control|
    control.vm.box = "bento/ubuntu-20.04-arm64"
    control.vm.hostname = "ozakkareSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    
    control.vm.provider "vmware_fusion" do |vb|
        vb.cpus = 1
        vb.memory = "1024"
      end

    control.vm.provision "shell", inline: <<-SHELL
      echo "Checking if server is ready..."
      while [ ! -f /vagrant/server_ready ]; do sleep 1; done
      echo "Server is ready, and token is available."
      K3S_URL=https://192.168.56.110:6443
      K3S_TOKEN=$(cat /vagrant/node_token)
      echo "Using K3S_URL=${K3S_URL}"
      echo "Using K3S_TOKEN=${K3S_TOKEN}"    
      curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -
    SHELL
  end
end
