Vagrant.configure("2") do |config|
    config.vm.define "mamali" do |control|
      control.vm.box = "bento/ubuntu-20.04"
      control.vm.hostname = "mamali"
      control.vm.network "private_network", ip: "192.168.56.112"
      control.vm.network "forwarded_port", guest: 8080, host: 8080
      control.vm.network "forwarded_port", guest: 80, host: 80
      control.vm.network "forwarded_port", guest: 443, host: 443
      control.vm.provider "vmware_fusion" do |vb|
        vb.cpus = 4
        vb.memory = "2048"
      end
      control.vm.provision "shell", path: "scripts/setup.sh"
      control.vm.provision "shell", path: "scripts/install_gitlab.sh"
    end
  end
  