Vagrant.configure("2") do |config|
  config.vm.define "mamali" do |control|
      control.vm.box = "ubuntu/focal64"
      control.vm.hostname = "mamali"
      control.vm.network "private_network", ip: "192.168.56.112"
      # Accessibility and Interaction: These settings make it easier to interact with services running within the VM directly 
      # from the host machine without needing to SSH into the VM for every interaction.
      control.vm.network "forwarded_port", guest: 8080, host: 8080
      control.vm.provider "virtualbox" do |vb|
          vb.cpus = 4
          vb.memory = "2048"
      end
      # Provision with external shell script
      control.vm.provision "shell", path: "setup.sh"
  end
end
