apiVersion: v1 #Specifies the version of the Kubernetes API
kind: Service
metadata:
  name: wil-playground-service
  labels:
    app: wil-playground
spec:
  type: NodePort #The type of service. NodePort exposes the service on each Node’s IP at a static port 
  ports:
  - port: 8888  # Port accessible inside the cluster, The port that this service exposes internally within the cluster.
    targetPort: 8888  # Container port to send requests to, The port on the container that the service forwards to
    nodePort: 30080  # Port accessible externally, The port on each node on which this service is exposed when using NodePort. External traffic to this port is forwarded to the port
    protocol: TCP
  selector: # Matches this service to Pods. This links the service to your deployment
    app: wil-playground
